---
title: ""
output: 
---



```{r}
qcdir = "/Volumes/Histopathology Shared Resource/CLINICAL/Nanostring/QC/"
data_dir = "/Volumes/Histopathology Shared Resource/CLINICAL/Nanostring/output/"
exclude=c("20190131_30102232840920","20190221_30102234070920") #earlier batch without controls or anything. did have one prostate sample that I wanted to see

qc=c()
batches = c()
for (batchid in list.files(data_dir)){
  if (!batchid %in% exclude){
    dat = read.csv(file = paste0(data_dir, batchid,"/qc_controls_positive.tsv"), sep="\t", check.names = F, stringsAsFactors = F, row.names = 1)
    
    #newdat = get_log(input_file = paste0(data_dir, batchid,"/4_LOG_2_NORMALIZED.tsv"))
    if (length(dat)>0){
      
      if (length(nrow(qc)) < 1){
        qc=dat[,c("Cell line", "Antibody", "status")]
        
      } else {
        qc=cbind(qc, status=dat[match(rownames(qc), rownames(dat)),c("status")])
      }
      colnames(qc)[which(colnames(qc)=="status")] = batchid
      batches = append(batches, batchid)
    }
  }
}

write.table(qc, file = sprintf("%s/qc_controls_pos_allbatches.txt", qcdir) ,sep="\t", quote = F, row.names = T, col.names = NA)

```

```{r}

data_dir = "/Volumes/Histopathology Shared Resource/CLINICAL/Nanostring/output/"
exclude=c("20190131_30102232840920","20190221_30102234070920") #earlier batch without controls or anything. did have one prostate sample that I wanted to see

qc=c()
batches = c()
for (batchid in list.files(data_dir)){
  if (!batchid %in% exclude){
    dat = read.csv(file = paste0(data_dir, batchid,"/qc_controls.tsv"), sep="\t", check.names = F, stringsAsFactors = F, row.names = 1)
    
    #newdat = get_log(input_file = paste0(data_dir, batchid,"/4_LOG_2_NORMALIZED.tsv"))
    if (length(dat)>0){
      
      if (length(nrow(qc)) < 1){
        qc=dat[,c("cellline", "antibody", "status")]
        
      } else {
        qc=cbind(qc, status=dat[match(rownames(qc), rownames(dat)),c("status")])
      }
      colnames(qc)[which(colnames(qc)=="status")] = batchid
      batches = append(batches, batchid)
    }
  }
}

write.table(qc, file = sprintf("%s/qc_controls_allbatches.txt", qcdir) ,sep="\t", quote = F, row.names = T, col.names = NA)

```